stages:
  format_data:
    cmd: python3 0_basic_data_formatting.py
    deps:
    - 0_basic_data_formatting.py
    - data/sample_submission.npy
    - data/test.npy
    - data/train.npy
    outs:
    - data/intermediate/test_df.csv
    - data/intermediate/train_df.csv
  features_differences:
    cmd: python3 1_features_diffs.py differences
    deps:
    - 1_features_diffs.py
    - data/intermediate/test_df.csv
    - data/intermediate/train_df.csv
    outs:
    - data/intermediate/test_features_differences.csv
    - data/intermediate/test_map_features_differences.pkl
    - data/intermediate/train_features_differences.csv
  ml_rf_differences:
    cmd: python3 2_machine_learning.py features_differences rf
    deps:
    - 2_machine_learning.py
    - data/intermediate/test_features_differences.csv
    - data/intermediate/test_map_features_differences.pkl
    - data/intermediate/train_features_differences.csv
    outs:
    - results/submission_features_differences_ml_rf_paramset_default.npy
  features_distances:
    cmd: python3 1_feature_engineering.py distances
    deps:
    - 1_feature_engineering.py
    - data/intermediate/test_df.csv
    - data/intermediate/train_df.csv
    outs:
    - data/intermediate/test_features_distances.csv
    - data/intermediate/test_map_features_distances.pkl
    - data/intermediate/train_features_distances.csv
  ml_rf_distances:
    cmd: python3 2_machine_learning.py features_distances rf
    deps:
    - 2_machine_learning.py
    - data/intermediate/test_features_distances.csv
    - data/intermediate/test_map_features_distances.pkl
    - data/intermediate/train_features_distances.csv
    outs:
    - results/submission_features_distances_ml_rf_paramset_default.npy
  features_distances_shifted:
    cmd: python3 1_feature_engineering.py distances_shifted
    deps:
    - 1_feature_engineering.py
    - data/intermediate/test_df.csv
    - data/intermediate/train_df.csv
    outs:
    - data/intermediate/test_features_distances_shifted.csv
    - data/intermediate/test_map_features_distances_shifted.pkl
    - data/intermediate/train_features_distances_shifted.csv
  ml_rf_distances_shifted:
    cmd: python3 2_machine_learning.py features_distances_shifted rf
    deps:
    - 2_machine_learning.py
    - data/intermediate/test_features_distances_shifted.csv
    - data/intermediate/test_map_features_distances_shifted.pkl
    - data/intermediate/train_features_distances_shifted.csv
    outs:
    - results/submission_features_distances_shifted_ml_rf_paramset_default.npy
  ml_gridsearchcv_distances_shifted:
    cmd: python3 2_machine_learning_gridsearch_cv.py features_distances_shifted
    deps:
    - 2_machine_learning_gridsearch_cv.py
    - data/intermediate/test_features_distances_shifted.csv
    - data/intermediate/test_map_features_distances_shifted.pkl
    - data/intermediate/train_features_distances_shifted.csv
    outs:
    - results/submission_features_distances_shifted_ml_gridsearch_cv_paramset_default.npy
    metrics:
    - results/summary_gridsearch_cv.json
  dl_baseline:
    cmd: python3 3_deep_learning.py baseline
    deps:
    - 3_deep_learning.py
    - data/sample_submission.npy
    - data/test.npy
    - data/train.npy
    params:
    - dl_baseline_settings.json:
      - epochs
    outs:
    - results/submission_dl_baseline_paramset_default.npy
    metrics:
    - results/summary_dl_baseline_paramset_default.json
  dl_lstm:
    cmd: python3 3_deep_learning.py lstm
    deps:
    - 3_deep_learning.py
    - data/sample_submission.npy
    - data/test.npy
    - data/train.npy
    params:
    - dl_lstm_settings.json:
      - epochs
    outs:
    - results/submission_dl_lstm_paramset_default.npy
    metrics:
    - results/summary_dl_lstm_paramset_default.json
