#!/bin/sh

#Initialization
#Data will be placed in ./data/

#Change to your own key...
API_KEY="0ba231d61506b40a4ae00df011cf0cb9" aicrowd login --api-key $API_KEY
aicrowd dataset download --challenge mabe-task-1-classical-classification

mkdir data
 
mv train.npy data/train.npy
mv test-release.npy data/test.npy
mv sample-submission.npy data/sample_submission.npy

#Step 0
#Format data (~5 minutes)
python 0_basic_data_formatting.py 

#Step 1
#Train DL 1D CNN model (~90 minutes)
python 1_deep_learning_stacking.py

#Step 2 (~3 hours, test feature file is ~100GB)
#Create features for model stacking
python 2_feature_engineering_stacking.py 

### NOTE ###

#Currently, this is run with the original 1D CNN predictions, since I'm checking I can reproduce results after step 1
#Will need to change the paths to point to the files generated by step 1 here, instead of the originals

############

#Step 3 (~20 minutes)
#Train ML model (XGB) with these features
python 3_machine_learning.py mars_distr_stacked_w_1dcnn xgb --test

### NOTE ###

#If I can get Step 2 to reproduce with the original 1DCNN probabilities, then I should be able to reproduce the final 
#predictions that I do have saved for the XGB model with the reweighting only (not the HMM, which I don't have saved...)

############

#Submit:
aicrowd submission create -c mabe-task-1-classical-classification \
                    -f results/submission_mars_distr_stacked_w_1dcnn_ml_xgb_paramset_default.npy

################################
#Check the answers are the same#
################################

#Step 0 -- checks out
md5sum ./data/intermediate/test_df.csv
md5sum ../../mabe/mabetask1_ml/data/intermediate/test_df.csv

md5sum ./data/intermediate/train_df.csv
md5sum ../../mabe/mabetask1_ml/data/intermediate/train_df.csv

#Step 1 -- doesn't yet check out... reproducibility in Keras may be complicated... will leave for now.
md5sum ./data/intermediate/deep_learning_stacking_prediction_probabilities_baseline_test_run_distances.npy
md5sum /home/blansdel/projects/mabe/mabetask1/deep_learning_stacking_prediction_probabilities_baseline_test_run_distances.npy

md5sum ./data/intermediate/deep_learning_stacking_prediction_probabilities_test_baseline_test_run_distances.npy
md5sum /home/blansdel/projects/mabe/mabetask1/deep_learning_stacking_prediction_probabilities_test_baseline_test_run_distances.npy

md5sum ./data/intermediate/deep_learning_stacking_predictions_baseline_test_run_distances.npy
md5sum /home/blansdel/projects/mabe/mabetask1/deep_learning_stacking_predictions_baseline_test_run_distances.npy

#Step 2 -- todo



#Step 3
# Don't have these saved :( Pretty stupid...

# Instead, here are some other sanity checks:

# Check 